Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2023-10, with the labels that each got.

#338 prefer logging user ids over emails
  server/handlers/getters.go
  server/handlers/handlers_test.go
  server/plugin.go
  server/plugin_test.go
Labels: 2: Dev Review

#347 metric: track the plugin start time
  server/metrics/metrics.go
Labels: 2: Dev Review

#348 metric: change event queue length & capacity
  server/handlers/handlers.go
  server/metrics/metrics.go
Labels: 2: Dev Review

#342 [MI-3606] Added the feature of limiting the no. of connected users allowed through a whitelist
  plugin.json
  server/api.go
  server/command.go
  server/command_test.go
  server/configuration.go
  server/plugin.go
  server/store/mocks/Store.go
  server/store/store.go
  server/store/store_test.go
Labels: Difficulty/3:Hard, Test Cases

#352 [MI-3634] Refactored some of the code according to review comments by Jesus
  server/command.go
  server/command_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/monitor/subscriptions.go
  server/monitor/subscriptions_test.go
  server/plugin_test.go
  server/store/mocks/Store.go
  server/store/store.go
  server/store/store_test.go
Labels: Difficulty/2:Medium, Test Cases

#355 [MI-3642] Add metrics to count upstream users
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/plugin.go
  server/plugin_test.go
Labels: Difficulty/2:Medium

#351 [MI-3629] Added cluster mutexes and solved the problem of race conditions for whitelist
  server/api.go
  server/command_test.go
  server/configuration.go
  server/plugin.go
  server/plugin_test.go
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
Labels: Difficulty/3:Hard, Test Cases

#382 delay metrics server start
  plugin.json
  server/plugin.go
Labels: 2: Dev Review
