Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2023-12, with the labels that each got.

#423 MM-55491: ensure handlers stop
  server/handlers/handlers.go
  server/handlers/worker.go
  server/handlers/worker_test.go
Labels: 4: Reviews Complete, QA/Deferred

#436 MM-55507: adopt ServeMetrics hook
  go.mod
  go.sum
  server/plugin.go
Labels: 4: Reviews Complete

#416 [MI-3750] Add info page for choosing primary platform
  assets/.gitkeep
  assets/close-icon.png
  assets/connection-icon.png
  assets/info-page/index.html
  assets/list-icon-info.png
  assets/list-icon-warn.png
  assets/mm-icon.png
  assets/msteams-icon.png
  assets/select-icon.png
  assets/trailing-icon.png
  server/api.go
  server/api_test.go
  server/iframe_test.go
Labels: 1: UX Review, 3: QA Review, Difficulty/2:Medium

#445 MM-55490: dont reset on configuration changes
  server/plugin.go
  server/plugin_test.go
Labels: 4: Reviews Complete, QA/Deferred

#443 adopt source available license
  LICENSE
  README.md
Labels: 1: PM Review, QA/Review Not Required

#446 only target linux-* architectures
  Makefile
  plugin.json
Labels: 2: Dev Review, QA/Review Not Required

#441 remove unused syncSince implementation
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/plugin.go
  server/plugin_test.go
Labels: 2: Dev Review, QA/Review Not Required

#439 restore metrics server stop
  server/plugin.go
Labels: 4: Reviews Complete, QA/Review Not Required

#447 Sync with starter template: dynamic versions
  .gitignore
  Makefile
  build/go.mod
  build/legacy.mk
  build/manifest/main.go
  build/pluginctl/main.go
  build/setup.mk
  build/sync/README.md
  build/sync/main.go
  build/sync/plan.yml
  build/sync/plan/actions.go
  build/sync/plan/actions_test.go
  build/sync/plan/checks.go
  build/sync/plan/checks_test.go
  build/sync/plan/git/file_history.go
  build/sync/plan/git/file_history_test.go
  build/sync/plan/plan.go
  build/sync/plan/plan_test.go
  build/sync/plan/setup.go
  build/sync/plan/testdata/a
  build/sync/plan/testdata/b/c
  plugin.json
  server/monitor/subscriptions.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete, QA/Review Not Required

#440 guard msteamsAppClient
  server/api.go
  server/command.go
  server/plugin.go
Labels: 2: Dev Review, QA/Review Not Required

#451 Build windows and darwin to solve build issues
  Makefile
  plugin.json
Labels: 2: Dev Review

#450 Restoring the generate make command
  Makefile
Labels: QA/Review Not Required

#454 MM-56364: fix metrics stop on configuration change
  server/metrics/dashboards/cloud.json
  server/plugin.go
Labels: 4: Reviews Complete, QA/Review Not Required

#422 Store the most recent changes time
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/plugin_test.go
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, QA/Deferred

#442 Refresh oauth tokens if needed
  server/api_test.go
  server/command_test.go
  server/message_hooks_test.go
  server/msteams/client.go
  server/msteams/client_timerlayer/timerlayer.go
  server/msteams/interface.go
  server/msteams/layer_generators/timer_layer.go.tmpl
  server/msteams/mocks/Client.go
  server/plugin.go
  server/plugin_test.go
Labels: 4: Reviews Complete, QA/Deferred

#455 build only linux* but support devs
  Makefile
  build/manifest/main.go
  plugin.json
Labels: 4: Reviews Complete
