Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2023-08, with the labels that each got.

#225 [MI-3327] Fixed the issue of replies and messages not being synced from Teams to MM for non-connected user
  README.md
  docs/azure_setup.md
  server/handlers/getters.go
  server/handlers/getters_test.go
  server/handlers/handlers_test.go
Labels: 3: QA Review

#246 [MI-3417] Added the documentation for slash commands
  README.md
  docs/azure_setup.md
Labels: Docs/Needed

#274 Remove debug logs for message hooks
  server/message_hooks.go
Labels: 2: Dev Review
