Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2023-11, with the labels that each got.

#385 Grafana Dashboard (Mattermost Cloud)
  server/metrics/dashboards/README.md
  server/metrics/dashboards/cloud.json
  server/metrics/dashboards/cloud.png
Labels: 2: Dev Review

#394 add recovery handler for activity handler worker
  server/handlers/handlers.go
  server/handlers/recovery_handler.go
  server/handlers/recovery_handler_test.go
Labels: 3: QA Review

#411 recovery.Go to stop unhandled panics in goroutines
  server/command.go
  server/handlers/attachments.go
  server/handlers/handlers.go
  server/monitor/monitor.go
  server/monitor/subscriptions.go
  server/plugin.go
  server/recovery/goroutine.go
  server/recovery/goroutine_test.go
  server/recovery/worker.go
  server/recovery/worker_test.go
Labels: QA/Deferred

#418 [MI-3773] Update documentation
  docs/plugin_setup.md
Labels: 2: Dev Review, QA/Review Not Required

#419 MM-55514: count panics & recover in background jobs too
  server/command.go
  server/handlers/attachments.go
  server/handlers/handlers.go
  server/handlers/worker.go
  server/handlers/worker_test.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/monitor/monitor.go
  server/monitor/subscriptions.go
  server/plugin.go
  server/recovery/goroutine.go
  server/recovery/goroutine_test.go
  server/recovery/worker.go
Labels: QA/Review Not Required

#417 [MI-3771] Add padding to enforced connected account modal
  webapp/src/components/enforceConnectedAccountModal.css
  webapp/src/components/enforceConnectedAccountModal.tsx
Labels: QA/Review Done, Difficulty/1:Easy

#415 [MI-3768] Fixed the issue of headings not working properly from MS Teams to MM
  server/markdown/markdown.go
  server/markdown/markdown_test.go
Labels: QA/Review Done, Difficulty/2:Medium, Test Cases

#228 [MI-3264] Update webapp base setup to use RTK query
  server/handlers/converters_test.go
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/enforceConnectedAccountModal.tsx
  webapp/src/constants/apiService.ts
  webapp/src/constants/index.ts
  webapp/src/containers/Rhs/index.tsx
  webapp/src/hooks/useApiRequestCompletionState.ts
  webapp/src/hooks/usePluginApi.ts
  webapp/src/index.tsx
  webapp/src/reducers/apiRequest/index.ts
  webapp/src/reducers/index.ts
  webapp/src/selectors/index.tsx
  webapp/src/services/index.ts
  webapp/src/types/common/index.d.ts
  webapp/src/types/common/service.d.ts
  webapp/src/types/common/store.d.ts
  webapp/src/types/mattermost-webapp/index.d.ts
  webapp/src/utils/index.ts
  webapp/tsconfig.json
  webapp/webpack.config.ts
  webapp/yarn.lock
Labels: Difficulty/3:Hard

#386 [MI-3709] Add logic to auto promote synthetic users on the basis of different auth services
  docs/plugin_setup.md
  go.mod
  go.sum
  plugin.go
  plugin.json
  server/api.go
  server/api_test.go
  server/command.go
  server/command_test.go
  server/configuration.go
  server/handlers/attachments.go
  server/handlers/attachments_test.go
  server/handlers/converters.go
  server/handlers/converters_test.go
  server/handlers/getters.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/handlers/mocks/PluginIface.go
  server/iframe_test.go
  server/main.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/monitor/monitor.go
  server/monitor/subscriptions_test.go
  server/msteams/client.go
  server/msteams/clientmodels/clientmodels.go
  server/plugin.go
  server/plugin_test.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/testutils/data.go
Labels: 3: QA Review, 3: Security Review

#424 Bump plugin version to v1.4.0
  plugin.json
Labels: 2: Dev Review, QA/Review Not Required
