Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2024-03, with the labels that each got.

#536 Fix replica conn leak
  server/plugin.go
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, QA/Deferred

#517 MM-56469 - change out library for converting html to markdown.
  go.mod
  go.sum
  server/markdown/markdown.go
  server/markdown/markdown_test.go
Labels: 4: Reviews Complete, QA/Deferred

#537 Adding e2e tests for selective syncing from mattermost to msteams
  server/ce2e/iframe_test.go
  server/ce2e/license_test.go
  server/ce2e/plugin_test.go
  server/preferences.go
  server/selective_sync.go
  server/testutils/containere2e/apimock.go
  server/testutils/containere2e/containere2e.go
  server/testutils/mmcontainer/testscontainer.go
Labels: 4: Reviews Complete, QA/Deferred

#500 MM-56776 Update mock to fix ChannelHasBeenCreated not being called for GMs
  server/automute_channel_test.go
  server/automute_test.go
Labels: 4: Reviews Complete, QA/Review Not Required

#539 Adding the remoteID migration, and making the synthetic user identification more robust
  server/ce2e/plugin_test.go
  server/command_test.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/mocks/PluginIface.go
  server/message_hooks.go
  server/plugin.go
  server/plugin_test.go
  server/selective_sync.go
  server/selective_sync_test.go
  server/store/mocks/Store.go
  server/store/sqlstore/helper_test.go
  server/store/sqlstore/migrations.go
  server/store/sqlstore/store.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
  server/testutils/containere2e/containere2e.go
Labels: 4: Reviews Complete, QA/Deferred

#547 Update text for Primary Platform selection
  assets/info-page/index.html
Labels: 1: PM Review, 1: UX Review, 2: Dev Review

#546 Allow self chats to sync when selective sync is true
  server/selective_sync.go
  server/selective_sync_test.go
Labels: 4: Reviews Complete, QA/Deferred

#552 add E2E formatting tests
  server/e2e/formatting_test.go
  server/markdown/markdown.go
Labels: QA/Deferred

#543 more verbose logging around subscriptions
  server/monitor/monitor.go
  server/monitor/subscriptions.go
  server/testutils/mock.go
Labels: QA/Review Not Required

#555 MM-56788 notify need to connect
  plugin.json
  server/command.go
  server/command_test.go
  server/configuration.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
Labels: 2: Dev Review

#550 [MM-56908] Make promote command accepts @ for both arguments
  server/command.go
  server/command_test.go
Labels: 2: Dev Review, 3: QA Review, QA/Deferred

#549 [MM-57072] Use ConstantTimeCompare to prevent timing attack
  server/api.go
Labels: QA/Deferred

#559 MM-57367: log when invite sent
  server/api.go
  webapp/src/index.tsx
Labels: 2: Dev Review

#556 use IsGroupOrDirect for clarity
  server/command.go
  server/message_hooks.go
Labels: QA/Review Not Required
