Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2024-04, with the labels that each got.

#571 MM-57120: show connected users stat
  server/api.go
  server/api_test.go
  webapp/src/client.ts
  webapp/src/index.tsx
  webapp/src/types/mattermost-webapp/index.d.ts
Labels: 4: Reviews Complete

#565 [RE:MM-57209] Set EmailVerified to true when autopromoting through hook
  server/message_hooks.go
  server/message_hooks_test.go
Labels: 2: Dev Review, QA/Deferred

#570 MM-57120: delay monitoring job on startup
  server/monitor/monitor.go
Labels: QA/Review Not Required

#561 [MM-56867] Fix metrics by not counting disabled users
  server/plugin.go
  server/plugin_test.go
Labels: 2: Dev Review, QA/Review Not Required

#569 MM-56809: support deleting messages from Mattermost
  server/message_hooks.go
  server/message_hooks_test.go
  server/msteams/client.go
  server/msteams/client_disconnectionlayer/disconnectionlayer.go
  server/msteams/client_timerlayer/timerlayer.go
  server/msteams/interface.go
  server/msteams/mocks/Client.go
Labels: 4: Reviews Complete, QA/Deferred

#567 MM-57534: monitor message creation delay
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
Labels: 4: Reviews Complete, QA/Review Not Required

#566 MM-57508: status slash command
  server/command.go
  server/command_test.go
Labels: 4: Reviews Complete, QA/Deferred

#545 Improve Users sync
  server/ce2e/plugin_test.go
  server/plugin.go
Labels: 4: Reviews Complete

#533 Add initial E2E tests on msteams change events
  server/ce2e/msteams_events_test.go
Labels: 4: Reviews Complete

#582 [MM-57568] Synthetic user created from DM/GM have wrong RemoteID
  go.mod
  server/handlers/getters.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/mocks/PluginIface.go
  server/plugin.go
Labels: 2: Dev Review

#568 MM-57506: use old CSS syntax
  assets/info-page/index.html
Labels: 2: Dev Review, QA/Deferred

#564 [MM-56982] UNIQUE index on msteamsuserid
  server/store/sqlstore/helper_test.go
  server/store/sqlstore/migrations.go
  server/store/sqlstore/migrations_test.go
  server/store/sqlstore/store.go
Labels: 4: Reviews Complete

#572 MM-57373 Fix connecting bot user
  server/api.go
  server/api_test.go
  server/command.go
Labels: 3: QA Review, 4: Reviews Complete, QA/Deferred

#562 [MM-56907] Log warn if updating the user fails when running the promote command
  server/command.go
  server/command_test.go
Labels: QA/Review Not Required

#563 MM-5701: reenable reattached plugin tests
  assets/assets.go
  build/go.sum
  go.mod
  go.sum
  plugin.json
  server/api.go
  server/command.go
  server/command_test.go
  server/configuration.go
  server/helper_test.go
  server/main_test.go
  server/plugin.go
  server/plugin_test.go
  server/preferences.go
  server/selective_sync_test.go
Labels: 2: Dev Review

#594 Set EmailVerified to true for all remote users during migration
  server/command.go
  server/handlers/getters.go
  server/handlers/getters_test.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/plugin.go
  server/plugin_test.go
  server/store/sqlstore/migrations.go
  server/store/sqlstore/store.go
Labels: 2: Dev Review

#596 Cherry pick of #594 for v1.11.1
  server/command.go
  server/command_test.go
  server/handlers/getters.go
  server/handlers/getters_test.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/plugin.go
  server/plugin_test.go
  server/store/sqlstore/migrations.go
  server/store/sqlstore/store.go
Labels: 2: Dev Review

#551 Adding more tests to the selective sync
  go.mod
  go.sum
  server/ce2e/plugin_test.go
  server/message_hooks.go
  server/testutils/containere2e/apimock.go
  server/testutils/containere2e/containere2e.go
Labels: 4: Reviews Complete

#592 Fix linter warnings for unused params
  server/automute_channel.go
  server/automute_preferences.go
  server/ce2e/msteams_events_test.go
Labels: 4: Reviews Complete

#583 MM-57563 - update method to allow self posts to sync, only if connected
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/mocks/PluginIface.go
  server/message_hooks.go
  server/selective_sync.go
  server/selective_sync_test.go
Labels: 4: Reviews Complete, QA/Deferred

#600 MM-57565 - Set root id if it exists on attachment sync warning
  server/message_hooks.go
Labels: 2: Dev Review, QA/Deferred

#538 Avoid crash if configuration is nil
  server/plugin.go
Labels: 2: Dev Review

#599 MM-57376, MM-57374, MM-57368: Connection Invites—whitelist and refinements
  plugin.json
  server/api.go
  server/command.go
  server/configuration.go
  server/connect.go
  server/helper_test.go
  server/plugin.go
  server/store/mocks/Store.go
  server/store/sqlstore/migrations.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
  server/store/storemodels/storemodels.go
  server/store/timerlayer/timerlayer.go
  webapp/src/client.ts
  webapp/src/components/admin_console/app_manifest_setting.tsx
  webapp/src/components/admin_console/get_connected_users_setting.tsx
  webapp/src/components/admin_console/invite_whitelist_setting.tsx
  webapp/src/components/appManifestSetting.tsx
  webapp/src/index.tsx
Labels: 3: QA Review

#593 MM-57507 Improve OAuth Flow
  server/api.go
  server/api_test.go
  server/automute_preferences.go
  server/automute_preferences_test.go
  server/automute_user_connect_test.go
  server/bot_messages.go
  server/command.go
  server/command_test.go
  server/connect.go
  server/helper_test.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/plugin.go
Labels: 3: QA Review

#603 MM-57906 Update platform preference when disconnecting
  server/command.go
  server/command_test.go
Labels: 4: Reviews Complete

#606 Use current_schema instead of public when checking for table existence
  server/store/sqlstore/migrations.go
Labels: 4: Reviews Complete

#612 Fix whitelist upload batching
  server/api.go
  server/store/sqlstore/store.go
Labels: 4: Reviews Complete

#584 MM-57508: status slash command
  server/command.go
  server/command_test.go
Labels: 4: Reviews Complete, QA/Deferred

#620 [MM-57821] Reduce number of calls to GetUser in syncUsers
  server/plugin.go
Labels: 4: Reviews Complete, QA/Deferred

#518 MM-56681 Use existing file Id if already uploaded
  server/handlers/attachments.go
  server/handlers/attachments_test.go
  server/handlers/converters.go
  server/handlers/converters_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
Labels: 4: Reviews Complete, QA/Deferred

#623 rewrite automute tests
  server/automute_channel_test.go
  server/automute_preferences_test.go
  server/automute_test.go
  server/helper_test.go
Labels: 4: Reviews Complete, QA/Review Not Required

#616 [MM-57918] Add Metrics for Primary Platform
  server/api.go
  server/api_test.go
  server/automute.go
  server/automute_preferences.go
  server/automute_preferences_test.go
  server/automute_user_connect_test.go
  server/command.go
  server/command_test.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/plugin.go
  server/preferences.go
  server/selective_sync.go
  server/selective_sync_test.go
  server/store/mocks/Store.go
  server/store/sqlstore/helper_test.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
  server/store/storemodels/storemodels.go
  server/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, QA/Deferred

#587 Add selective sync e2e testing from msteams to mattermost
  server/ce2e/msteams_events_test.go
Labels: 4: Reviews Complete
