Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2024-08, with the labels that each got.

#727 MM-60005: dont notify if present
  server/bot_messages.go
  server/credentials.go
  server/handlers.go
  server/handlers_test.go
  server/metrics/dashboards/dashboard.json
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/msteams/client.go
  server/msteams/client_disconnectionlayer/disconnectionlayer.go
  server/msteams/client_timerlayer/timerlayer.go
  server/msteams/clientmodels/clientmodels.go
  server/msteams/interface.go
  server/msteams/mocks/Client.go
  server/notifications.go
  server/presence.go
  server/store/mocks/Store.go
  server/store/sqlstore/public_methods.go
  server/store/timerlayer/timerlayer.go
  server/subscriptions.go
Labels: 2: Dev Review

#728 Remove unused code
  server/plugin.go
Labels: 4: Reviews Complete, QA/Review Not Required

#729 remove unused LastActivityAt handling
  server/handlers.go
  server/metrics/mocks/Metrics.go
  server/store/mocks/Store.go
  server/store/sqlstore/public_methods.go
  server/store/sqlstore/store.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete
