Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2024-02, with the labels that each got.

#480 Improved logging
  server/api.go
  server/api_mock.go
  server/api_test.go
  server/command.go
  server/command_test.go
  server/handlers/attachments.go
  server/handlers/attachments_test.go
  server/handlers/converters.go
  server/handlers/converters_test.go
  server/handlers/getters.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/iframe.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/monitor/monitor.go
  server/monitor/subscriptions.go
  server/monitor/subscriptions_test.go
  server/msteams/client.go
  server/plugin.go
  server/plugin_test.go
  server/store/sqlstore/store.go
  server/testutils/mock.go
Labels: QA/Review Not Required

#481 remove avatar handling
  server/api.go
  server/api_test.go
  server/handlers/converters.go
  server/handlers/converters_test.go
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
Labels: 2: Dev Review

#493 require enterprise license
  server/ce2e/license_test.go
  server/plugin.go
  server/plugin_test.go
  server/testutils/containere2e/containere2e.go
  server/testutils/mmcontainer/testscontainer.go
Labels: QA/Deferred

#482 drop support for MySQL
  README.md
  go.mod
  server/plugin.go
  server/store/sqlstore/helper_test.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/testutils/containere2e/containere2e.go
Labels: 2: Dev Review, QA/Review Not Required

#490 Drop job status
  server/monitor/monitor.go
  server/plugin.go
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
Labels: QA/Review Not Required

#491 only expose metrics via ServeMetrics
  server/metrics/server.go
  server/plugin.go
Labels: QA/Review Not Required

#470 Update the select platform site with the latest designs
  assets/close-icon.png
  assets/close-icon.svg
  assets/connection-icon.png
  assets/fonts/Metropolis-SemiBold.woff
  assets/fonts/README.md
  assets/fonts/open-sans-v18-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-300italic.woff
  assets/fonts/open-sans-v18-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-300italic.woff2
  assets/fonts/open-sans-v18-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-600.woff
  assets/fonts/open-sans-v18-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-600.woff2
  assets/fonts/open-sans-v18-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular.woff
  assets/fonts/open-sans-v18-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular.woff2
  assets/info-page/index.html
  assets/list-icon-warn.png
  assets/list-icon-warn.svg
  assets/mm-icon.png
  assets/mm-icon.svg
  assets/msteams-icon.png
  assets/msteams-icon.svg
  assets/select-icon.png
  assets/select-icon.svg
  assets/trailing-icon.png
  assets/trailing-icon.svg
Labels: 4: Reviews Complete, QA/Deferred

#496 Disable reactions / files attachments / linked channels by default
  plugin.json
  server/command.go
  server/command_test.go
  server/configuration.go
  server/handlers/attachments.go
  server/handlers/attachments_test.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/handlers/mocks/PluginIface.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/metrics/metrics.go
  server/plugin.go
  server/testutils/containere2e/containere2e.go
Labels: 2: Dev Review

#498 set deprecated parameter to nil
  server/api.go
Labels: 4: Reviews Complete, QA/Review Not Required

#497 stop managing global chats subscription if disabled
  server/monitor/monitor.go
  server/monitor/subscriptions.go
  server/monitor/subscriptions_test.go
  server/plugin.go
Labels: QA/Review Not Required

#503 Change .nvmrc + add some docs
  .nvmrc
  docs/developer_docs.md
Labels: 2: Dev Review, QA/Review Not Required

#505 add user_id to various logs in sync_user job
  server/plugin.go
Labels: 2: Dev Review, QA/Review Not Required

#501 Reformat configuration docs
  docs/plugin_setup.md
Labels: 2: Dev Review

#499 Remove comments for commented out features
  server/api.go
  webapp/src/index.tsx
Labels: QA/Deferred

#477 MM-56496/MM-56497 Automute linked channels when a user sets their primary platform to Teams
  server/api.go
  server/automute.go
  server/automute_preferences.go
  server/automute_preferences_test.go
  server/automute_test.go
  server/preferences.go
  server/utils.go
Labels: 4: Reviews Complete, QA/Deferred

#502 avoid burying errors during test setup
  server/store/sqlstore/helper_test.go
Labels: 2: Dev Review, QA/Review Not Required

#504 MM-56778 - handle self chats
  server/msteams/client.go
Labels: QA/Deferred

#479 MM-56501 Enable/disable automuting when a user connects/disconnects
  .golangci.yml
  server/api.go
  server/automute.go
  server/automute_channel.go
  server/automute_channel_test.go
  server/automute_preferences.go
  server/automute_test.go
  server/automute_user_connect.go
  server/automute_user_connect_test.go
  server/command.go
  server/command_test.go
Labels: 4: Reviews Complete, QA/Deferred

#507 fix Continue button during oAuth flow
  assets/info-page/index.html
Labels: 4: Reviews Complete, QA/Deferred

#492 drop -sync, renaming to just msteams
  README.md
  assets/plugin-icon.png
  assets/plugin-icon.svg
  docs/azure_setup.md
  docs/developer_docs.md
  docs/plugin_setup.md
  go.mod
  plugin.json
  server/api.go
  server/api_mock.go
  server/api_nomock.go
  server/api_test.go
  server/automute_test.go
  server/ce2e/iframe_test.go
  server/ce2e/license_test.go
  server/ce2e/plugin_test.go
  server/command.go
  server/command_test.go
  server/credentials.go
  server/e2e/channels_test.go
  server/e2e/dms_test.go
  server/e2e/main_test.go
  server/handlers/attachments.go
  server/handlers/attachments_test.go
  server/handlers/converters.go
  server/handlers/converters_test.go
  server/handlers/getters.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/handlers/mocks/PluginIface.go
  server/iframe.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/monitor/monitor.go
  server/monitor/subscriptions.go
  server/monitor/subscriptions_test.go
  server/msteams/client.go
  server/msteams/client_disconnectionlayer/disconnectionlayer.go
  server/msteams/client_test.go
  server/msteams/client_timerlayer/timerlayer.go
  server/msteams/interface.go
  server/msteams/layer_generators/disconnection_layer.go.tmpl
  server/msteams/layer_generators/timer_layer.go.tmpl
  server/msteams/mocks/Client.go
  server/plugin.go
  server/plugin_test.go
  server/store/layer_generators/timer_layer.go.tmpl
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
  server/testutils/containere2e/containere2e.go
  server/testutils/data.go
  webapp/src/index.tsx
Labels: QA/Deferred

#509 avoid naming files plugin-*
  assets/icon.png
  assets/icon.svg
  plugin.json
  public/icon.svg
  server/command.go
  server/plugin.go
  webapp/src/index.tsx
Labels: 2: Dev Review, QA/Review Not Required

#510 fix closeInfoPage to call on promise resolution
  assets/info-page/index.html
Labels: 2: Dev Review

#511 update google.com links
  webapp/src/index.tsx
Labels: 2: Dev Review, QA/Deferred

#515 avoid assets error
  assets/assets.go
Labels: 4: Reviews Complete, QA/Review Not Required

#520 Move LICENSE to bottom of README
  README.md
Labels: QA/Review Not Required
