Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2024-05, with the labels that each got.

#601 Track status_code as part of the MSGraphClient method duration
  server/api_test.go
  server/message_hooks_test.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/msteams/client_timerlayer/timerlayer.go
  server/msteams/layer_generators/main.go
  server/msteams/layer_generators/timer_layer.go.tmpl
Labels: 4: Reviews Complete

#602 Add DB replica support
  server/plugin.go
  server/store/sqlstore/helper_test.go
  server/store/sqlstore/migrations.go
  server/store/sqlstore/migrations_test.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/testutils/containere2e/containere2e.go
Labels: 4: Reviews Complete

#626 [MM-57197] Weekly active users
  .tool-versions
  server/api.go
  server/api_test.go
  server/handlers/getters.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/plugin.go
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
  server/store/storemodels/storemodels.go
  server/store/timerlayer/timerlayer.go
Labels: 2: Dev Review, QA/Deferred

#642 (chore) Rename plugin's userID to botUsertID
  server/automute_preferences_test.go
  server/bot_messages.go
  server/command.go
  server/command_test.go
  server/connect.go
  server/message_hooks.go
  server/plugin.go
  server/plugin_test.go
Labels: 2: Dev Review, QA/Review Not Required

#629 MM-57535 Don't automute guests nor bots
  server/automute.go
  server/automute_channel.go
  server/automute_channel_test.go
  server/automute_test.go
  server/helper_test.go
Labels: 2: Dev Review

#645 Migrate setup/config/usage to Product Docs
  README.md
  docs/azure_setup.md
  docs/brightscout-msteams-sync-v1.0.png
  docs/developer_docs.md
  docs/faqs.md
  docs/plugin_setup.md
Labels: 4: Reviews Complete

#640 [MM-57351] Add weekly users sending/receiving site stats
  server/api.go
  server/api_test.go
  server/store/sqlstore/store_test.go
  webapp/src/client.ts
  webapp/src/index.tsx
  webapp/src/types/mattermost-webapp/index.d.ts
Labels: 4: Reviews Complete

#637 MM-58052 - Only sync if a user in the chat is remote
  server/ce2e/msteams_events_test.go
  server/ce2e/plugin_test.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/mocks/PluginIface.go
  server/message_hooks.go
  server/selective_sync.go
  server/selective_sync_test.go
Labels: QA/Deferred

#628 Rewrite API tests
  .golangci.yml
  go.mod
  server/api.go
  server/api_test.go
  server/helper_test.go
Labels: 2: Dev Review

#643 [MM-58155] Separate DM/GM option
  build/manifest/main.go
  plugin.json
  server/configuration.go
  server/handlers/attachments.go
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/handlers/mocks/PluginIface.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/monitor/monitor.go
  server/monitor/subscriptions.go
  server/monitor/subscriptions_test.go
  server/plugin.go
  server/testutils/containere2e/containere2e.go
Labels: 2: Dev Review, QA/Deferred

#625 [MM-57702] Add RequestIDs+TS in msgraph client errors
  .nvmrc
  server/msteams/client.go
Labels: 2: Dev Review, QA/Review Not Required

#648 MM-58134- Disconnect should not be ephemeral message
  server/bot_messages.go
  server/command.go
Labels: 4: Reviews Complete, QA/Deferred

#627 Fix possible race condition that can lead to duplicated messages
  server/handlers/getters_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/handlers/mocks/PluginIface.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/metrics/metrics.go
  server/plugin.go
Labels: QA/Deferred

#656 [MM-58322] Add notification preference slash command
  server/automute.go
  server/command.go
  server/command_test.go
  server/plugin.go
  server/preferences.go
  server/preferences_test.go
  server/store/storemodels/storemodels.go
Labels: 2: Dev Review

#655 Collapse handlers into root
  server/attachments.go
  server/attachments_test.go
  server/converters.go
  server/converters_test.go
  server/getters.go
  server/getters_test.go
  server/handlers.go
  server/handlers/mocks/PluginIface.go
  server/handlers_test.go
  server/notifications.go
  server/plugin.go
  server/plugin_test.go
  server/worker.go
  server/worker_test.go
Labels: 2: Dev Review, QA/Review Not Required

#631 MM-57853: Whitelist Restricted (simplified)
  plugin.json
  server/api.go
  server/api_test.go
  server/bot_messages_test.go
  server/command.go
  server/command_test.go
  server/configuration.go
  server/connect.go
  server/connect_test.go
  server/helper_test.go
  server/store/sqlstore/store.go
  webapp/src/components/admin_console/connected_users_whitelist_setting.tsx
  webapp/src/index.tsx
Labels: 2: Dev Review, QA/Deferred

#657 [MM-58290] Add UI to select notification preference.
  server/api.go
  server/api_test.go
  server/command.go
  server/command_test.go
  server/helper_test.go
  server/websocket_events.go
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/index.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/selectors/index.tsx
  webapp/src/types/actions.ts
  webapp/src/types/mattermost-webapp/index.d.ts
  webapp/src/types/websocket.ts
  webapp/src/user_settings.ts
  webapp/src/websocket_handler.ts
Labels: 2: Dev Review

#652 Sync remote config
  plugin.json
  server/automute.go
  server/automute_channel_test.go
  server/automute_preferences.go
  server/automute_preferences_test.go
  server/automute_test.go
  server/ce2e/msteams_events_test.go
  server/ce2e/plugin_test.go
  server/command.go
  server/configuration.go
  server/handlers.go
  server/handlers_test.go
  server/message_hooks.go
  server/metrics/metrics.go
  server/plugin.go
  server/selective_sync.go
  server/selective_sync_test.go
  server/store/sqlstore/store.go
Labels: QA/Deferred

#658 Rewrite message hooks tests part2
  go.mod
  go.sum
  server/automute_channel_test.go
  server/helper_test.go
  server/main_test.go
  server/message.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/message_test.go
  server/permutation_test.go
  server/reaction.go
  server/reaction_test.go
Labels: 2: Dev Review

#660 [MM-58300 + MM-58346] honour user pref + update their last messaged received at
  server/notifications.go
Labels: 2: Dev Review

#659 [MM-58298] Add notification welcome message
  assets/account-connected/index.html
  assets/enable_notifications.gif
  assets/pagebg.jpeg
  server/api.go
  server/api_test.go
  server/bot_messages.go
  server/bot_messages_test.go
  server/plugin.go
  server/plugin_test.go
Labels: 2: Dev Review

#667 MM-58344: style notifications
  server/bot_messages.go
  server/handlers_test.go
  server/helper_test.go
  server/notifications.go
Labels: 2: Dev Review

#666 [MM-58308] Add number of attachments
  server/bot_messages.go
  server/handlers_test.go
  server/notifications.go
Labels: 2: Dev Review

#670 [MM-58374] Turn off notification preference on disconnect
  server/command.go
  server/command_test.go
Labels: 2: Dev Review

#672 MM-58436: Notifications review feedback
  assets/account-connected/index.html
  server/api.go
  server/api_test.go
  server/bot_messages.go
  server/bot_messages_test.go
  server/command.go
  server/command_test.go
  server/msteams/client.go
  server/msteams/clientmodels/clientmodels.go
  server/notifications.go
  webapp/src/user_settings.ts
Labels: 1: UX Review, 2: Dev Review

#673 rm -fr Teams Primary preference
  assets/info-page/index.html
  server/api.go
  server/api_test.go
  server/automute.go
  server/automute_channel.go
  server/automute_channel_test.go
  server/automute_preferences.go
  server/automute_preferences_test.go
  server/automute_test.go
  server/automute_user_connect.go
  server/automute_user_connect_test.go
  server/bot_messages.go
  server/ce2e/msteams_events_test.go
  server/ce2e/plugin_test.go
  server/command.go
  server/command_test.go
  server/connect.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/plugin.go
  server/preferences.go
  server/selective_sync.go
  server/selective_sync_test.go
  server/store/mocks/Store.go
  server/store/sqlstore/public_methods.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
  server/store/storemodels/storemodels.go
  server/store/timerlayer/timerlayer.go
  webapp/src/user_settings.ts
Labels: 2: Dev Review

#677 MM-58287: track notification metrics
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/notifications.go
Labels: 2: Dev Review

#675 MM-56924: Connection invite metrics
  server/api.go
  server/api_test.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/plugin.go
  webapp/src/client.ts
Labels: 4: Reviews Complete
