Repository mattermost/mattermost-plugin-msteams, pull requests merged in 2024-01, with the labels that each got.

#468 Worker & plugin version metrics
  plugin.go
  server/handlers/handlers.go
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/monitor/monitor.go
  server/plugin.go
  server/plugin_test.go
Labels: 4: Reviews Complete, QA/Review Not Required

#429 Removing transactions outside the store
  server/command.go
  server/command_test.go
  server/handlers/handlers.go
  server/handlers/handlers_test.go
  server/message_hooks.go
  server/message_hooks_test.go
  server/monitor/subscriptions.go
  server/monitor/subscriptions_test.go
  server/plugin_test.go
  server/store/layer_generators/timer_layer.go.tmpl
  server/store/mocks/Store.go
  server/store/sqlstore/store.go
  server/store/sqlstore/store_test.go
  server/store/store.go
  server/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, QA/Deferred

#460 Adding whitelist limit metric
  server/metrics/metrics.go
  server/metrics/mocks/Metrics.go
  server/plugin.go
Labels: QA/Deferred

#469 fix release notes url generation
  build/manifest/main.go
Labels: 4: Reviews Complete, QA/Review Not Required

#472 initialize API only once
  server/api_test.go
  server/plugin.go
  server/plugin_test.go
Labels: 2: Dev Review

#475 CE2E fixes, support MacOS
  Makefile
  build/manifest/main.go
  server/testutils/containere2e/containere2e.go
  server/testutils/mmcontainer/testscontainer.go
Labels: 2: Dev Review

#476 fix defaultGoOs/defaultGoArch when not exported
  build/manifest/main.go
Labels: 4: Reviews Complete

#473 Better error msg on test fail
  server/ce2e/iframe_test.go
Labels: 4: Reviews Complete, QA/Review Not Required

#453 Notify user when reconnection is needed
  server/msteams/client.go
  server/msteams/client_disconnectionlayer/disconnectionlayer.go
  server/msteams/layer_generators/disconnection_layer.go.tmpl
  server/msteams/layer_generators/main.go
  server/plugin.go
Labels: 4: Reviews Complete

#478 Fixing issue on reconnect required notification
  server/msteams/client.go
  server/msteams/client_disconnectionlayer/disconnectionlayer.go
  server/msteams/layer_generators/disconnection_layer.go.tmpl
Labels: 3: QA Review
